# Generated by Django 2.0.5 on 2018-06-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('account', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
